version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - .:/app
    environment:
     - WATCHPACK_POLLING=true
     - PATH=${PATH}:/app/node_modules/.bin
    ports:
     - "3000:3000"
    command: sh -c "cd src && npm run dev"